# CMake generated Testfile for 
# Source directory: D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests
# Build directory: D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-bert-bge "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-bert-bge "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-bert-bge "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-bert-bge "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-bert-bge.gguf")
  set_tests_properties(test-tokenizer-0-bert-bge PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;75;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-bert-bge NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-command-r "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-command-r "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-command-r "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-command-r "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-command-r.gguf")
  set_tests_properties(test-tokenizer-0-command-r PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;76;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-command-r NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-deepseek-coder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-coder.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-deepseek-coder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-coder.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-deepseek-coder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-coder.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-deepseek-coder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-coder.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-coder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;77;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-deepseek-coder NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-deepseek-llm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-llm.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;78;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-deepseek-llm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-llm.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;78;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-deepseek-llm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-llm.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;78;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-deepseek-llm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-deepseek-llm.gguf")
  set_tests_properties(test-tokenizer-0-deepseek-llm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;78;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-deepseek-llm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-falcon "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;79;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-falcon "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;79;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-falcon "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;79;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-falcon "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-falcon.gguf")
  set_tests_properties(test-tokenizer-0-falcon PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;79;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-falcon NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-gpt-2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;80;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-gpt-2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;80;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-gpt-2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;80;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-gpt-2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-gpt-2.gguf")
  set_tests_properties(test-tokenizer-0-gpt-2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;80;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-gpt-2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-llama-bpe "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;81;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-llama-bpe "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;81;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-llama-bpe "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;81;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-llama-bpe "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-bpe.gguf")
  set_tests_properties(test-tokenizer-0-llama-bpe PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;81;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-llama-bpe NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-llama-spm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;82;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-llama-spm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;82;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-llama-spm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;82;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-llama-spm "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-llama-spm.gguf")
  set_tests_properties(test-tokenizer-0-llama-spm PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;82;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-llama-spm NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-mpt "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-mpt.gguf")
  set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-mpt "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-mpt.gguf")
  set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-mpt "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-mpt.gguf")
  set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-mpt "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-mpt.gguf")
  set_tests_properties(test-tokenizer-0-mpt PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;83;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-mpt NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-phi-3 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-phi-3 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-phi-3 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-phi-3 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-phi-3.gguf")
  set_tests_properties(test-tokenizer-0-phi-3 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;84;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-phi-3 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-qwen2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-qwen2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-qwen2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-qwen2 "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-qwen2.gguf")
  set_tests_properties(test-tokenizer-0-qwen2 PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;85;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-qwen2 NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-refact "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-refact "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-refact "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-refact "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-refact.gguf")
  set_tests_properties(test-tokenizer-0-refact PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;86;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-refact NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-tokenizer-0-starcoder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-tokenizer-0-starcoder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-tokenizer-0-starcoder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-tokenizer-0-starcoder "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-tokenizer-0.exe" "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/../models/ggml-vocab-starcoder.gguf")
  set_tests_properties(test-tokenizer-0-starcoder PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;24;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;87;llama_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-tokenizer-0-starcoder NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-log "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-log.exe")
  set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;133;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-log "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-log.exe")
  set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;133;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-log "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-log.exe")
  set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;133;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-log "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-log.exe")
  set_tests_properties(test-log PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;133;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-log NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-arg-parser "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-arg-parser.exe")
  set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-arg-parser "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-arg-parser.exe")
  set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-arg-parser "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-arg-parser.exe")
  set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-arg-parser "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-arg-parser.exe")
  set_tests_properties(test-arg-parser PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;134;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-arg-parser NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-chat-template "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;135;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-chat-template "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;135;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-chat-template "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;135;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-chat-template "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-chat-template.exe")
  set_tests_properties(test-chat-template PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;135;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-chat-template NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gguf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-gguf.exe")
  set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;138;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gguf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-gguf.exe")
  set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;138;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gguf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-gguf.exe")
  set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;138;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gguf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-gguf.exe")
  set_tests_properties(test-gguf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;138;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-gguf NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-backend-ops "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;139;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-backend-ops "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;139;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-backend-ops "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;139;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-backend-ops "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-backend-ops.exe")
  set_tests_properties(test-backend-ops PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;139;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-backend-ops NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-model-load-cancel "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;141;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-model-load-cancel "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;141;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-model-load-cancel "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;141;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-model-load-cancel "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-model-load-cancel.exe")
  set_tests_properties(test-model-load-cancel PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;141;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-model-load-cancel NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-autorelease "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;142;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-autorelease "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;142;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-autorelease "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;142;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-autorelease "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-autorelease.exe")
  set_tests_properties(test-autorelease PROPERTIES  LABELS "model" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;142;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-autorelease NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-barrier "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-barrier.exe")
  set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;146;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-barrier "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-barrier.exe")
  set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;146;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-barrier "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-barrier.exe")
  set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;146;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-barrier "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-barrier.exe")
  set_tests_properties(test-barrier PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;146;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-barrier NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-quantize-fns "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;147;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-quantize-fns "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;147;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-quantize-fns "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;147;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-quantize-fns "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-quantize-fns.exe")
  set_tests_properties(test-quantize-fns PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;147;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-quantize-fns NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-quantize-perf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;148;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-quantize-perf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;148;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-quantize-perf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;148;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-quantize-perf "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-quantize-perf.exe")
  set_tests_properties(test-quantize-perf PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;148;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-quantize-perf NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-rope "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Debug/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;149;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-rope "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/Release/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;149;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-rope "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/MinSizeRel/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;149;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-rope "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/build_cpu/bin/RelWithDebInfo/test-rope.exe")
  set_tests_properties(test-rope PROPERTIES  LABELS "main" WORKING_DIRECTORY "." _BACKTRACE_TRIPLES "D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;61;add_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;149;llama_target_and_test;D:/work_space/MobileLMAPP/deploy/util/llama.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-rope NOT_AVAILABLE)
endif()
